services:
  server:
    image: ghcr.io/ggml-org/llama.cpp:server-vulkan
    container_name: llama.cpp.server
    restart: always
    shm_size: '16gb'
    volumes:
      - ~/.models:/models
      - ./config.ini:/config.ini
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    group_add:
      - video
    ports:
      - "8080:8080"
    command: [
      "--models-dir", "/models",
      "--models-preset", "/config.ini",
      "--host", "0.0.0.0",
      "--port", "8080",
      "--parallel", "1",
    ]
    environment:
      - HSA_OVERRIDE_GFX_VERSION=12.0.0
  downloader:
    build:
      context: .
      dockerfile: Dockerfile.hf
    container_name: hf.downloader
    profiles: ["tools"]
    volumes:
      - ~/.models:/models
    working_dir: /models
    environment:
      - HF_HOME=/models/.cache
      - HF_TRANSFER=1
